"""全局常量定义 (Spec §20)"""

# 交易方向
DIRECTION_LONG = 1
DIRECTION_SHORT = -1
DIRECTION_NEUTRAL = 0

# 市场状态 (Spec §8.3)
REGIME_TRENDING = 'TRENDING'
REGIME_RANGING = 'RANGING'
REGIME_EXTREME = 'EXTREME'
REGIME_UNKNOWN = 'UNKNOWN'

# 评级 (Spec §8.2)
GRADE_A = 'A'
GRADE_B = 'B'
GRADE_C = 'C'
GRADE_D = 'D'

# 策略类型 (Spec §10)
SETUP_PULLBACK = 'pullback'
SETUP_COMPRESSION_BREAKOUT = 'compression_breakout'

# 平仓原因 (Spec §14)
CLOSE_STOP_LOSS = 'stop_loss'
CLOSE_TP1 = 'tp1'
CLOSE_TP2 = 'tp2'
CLOSE_TIME_STOP = 'time_stop'
CLOSE_SCORE_DROP = 'trend_score_drop'
CLOSE_DIRECTION_INVALID = 'direction_invalid'
CLOSE_REVERSE_SIGNAL = 'reverse_signal'
CLOSE_BREAKOUT_FAIL = 'breakout_fail'

# 风控限制 (Spec §3.3)
DEFAULT_RISK_PER_TRADE = 0.004
DEFAULT_DAILY_LOSS_LIMIT = 0.03
DEFAULT_MAX_CONSECUTIVE_LOSSES = 5
DEFAULT_MAX_POSITIONS = 3
DEFAULT_SAME_DIRECTION_RISK = 0.012
DEFAULT_TOTAL_RISK = 0.016

# 时间常量
FUNDING_INTERVAL_HOURS = 8
BARS_PER_HOUR_15M = 4
BARS_PER_HOUR_5M = 12
BARS_PER_HOUR_1M = 60

# 交易所
FEE_RATE_TAKER = 0.0004
FEE_RATE_MAKER = 0.0002
SLIPPAGE_BPS = 2  # 2 basis points
MAX_SLIPPAGE_PCT = 0.15

# 回测通过标准 (Spec §23.4)
PASS_MAX_DRAWDOWN = 0.15
PASS_MIN_WIN_RATE = 0.38
PASS_MIN_AVG_RR = 1.7
PASS_MIN_PROFIT_FACTOR = 1.25
PASS_MIN_SAMPLE_SIZE = 200
