<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Areas;
use Illuminate\Support\Facades\DB;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
public function run(): void
    {
        $areas = [
            // Malaysia: Johor (MY-01)
            ['area_code' => 'MYS-01-JB', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Johor Bahru', 'area_type' => 'city', 'postal_code' => '80000'],
            ['area_code' => 'MYS-01-BP', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Batu Pahat', 'area_type' => 'district', 'postal_code' => '83000'],
            ['area_code' => 'MYS-01-KL', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Kluang', 'area_type' => 'district', 'postal_code' => '86000'],
            ['area_code' => 'MYS-01-KT', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Kota Tinggi', 'area_type' => 'district', 'postal_code' => '81900'],
            ['area_code' => 'MYS-01-MR', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Muar', 'area_type' => 'district', 'postal_code' => '84000'],
            ['area_code' => 'MYS-01-PT', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Pontian', 'area_type' => 'district', 'postal_code' => '82000'],
            ['area_code' => 'MYS-01-SG', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Segamat', 'area_type' => 'district', 'postal_code' => '85000'],
            ['area_code' => 'MYS-01-KU', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Kulai', 'area_type' => 'district', 'postal_code' => '81000'],
            ['area_code' => 'MYS-01-TG', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Tangkak', 'area_type' => 'district', 'postal_code' => '84900'],
            ['area_code' => 'MYS-01-MS', 'country_code' => 'MYS', 'state_code' => 'MY-01', 'area_name' => 'Mersing', 'area_type' => 'district', 'postal_code' => '86800'],
            // Malaysia: Kedah (MY-02)
            ['area_code' => 'MYS-02-AS', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Alor Setar', 'area_type' => 'city', 'postal_code' => '05000'],
            ['area_code' => 'MYS-02-KK', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Kota Setar', 'area_type' => 'district', 'postal_code' => '06000'],
            ['area_code' => 'MYS-02-KB', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Kubang Pasu', 'area_type' => 'district', 'postal_code' => '06010'],
            ['area_code' => 'MYS-02-PD', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Pendang', 'area_type' => 'district', 'postal_code' => '06700'],
            ['area_code' => 'MYS-02-KL', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Kuala Muda', 'area_type' => 'district', 'postal_code' => '08000'],
            ['area_code' => 'MYS-02-YT', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Yan', 'area_type' => 'district', 'postal_code' => '06900'],
            ['area_code' => 'MYS-02-SK', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Sik', 'area_type' => 'district', 'postal_code' => '08200'],
            ['area_code' => 'MYS-02-BL', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Baling', 'area_type' => 'district', 'postal_code' => '09100'],
            ['area_code' => 'MYS-02-PK', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Padang Terap', 'area_type' => 'district', 'postal_code' => '06300'],
            ['area_code' => 'MYS-02-LG', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Langkawi', 'area_type' => 'district', 'postal_code' => '07000'],
            ['area_code' => 'MYS-02-KH', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Kulim', 'area_type' => 'district', 'postal_code' => '09000'],
            ['area_code' => 'MYS-02-BD', 'country_code' => 'MYS', 'state_code' => 'MY-02', 'area_name' => 'Bandar Baharu', 'area_type' => 'district', 'postal_code' => '09400'],
            // Malaysia: Kelantan (MY-03)
            ['area_code' => 'MYS-03-KB', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Kota Bharu', 'area_type' => 'district', 'postal_code' => '15000'],
            ['area_code' => 'MYS-03-PC', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Pasir Mas', 'area_type' => 'district', 'postal_code' => '17000'],
            ['area_code' => 'MYS-03-TM', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Tumpat', 'area_type' => 'district', 'postal_code' => '16000'],
            ['area_code' => 'MYS-03-BC', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Bachok', 'area_type' => 'district', 'postal_code' => '16300'],
            ['area_code' => 'MYS-03-TN', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Tanah Merah', 'area_type' => 'district', 'postal_code' => '17500'],
            ['area_code' => 'MYS-03-PP', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Pasir Puteh', 'area_type' => 'district', 'postal_code' => '16800'],
            ['area_code' => 'MYS-03-MC', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Machang', 'area_type' => 'district', 'postal_code' => '18500'],
            ['area_code' => 'MYS-03-KL', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Kuala Krai', 'area_type' => 'district', 'postal_code' => '18000'],
            ['area_code' => 'MYS-03-GJ', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Gua Musang', 'area_type' => 'district', 'postal_code' => '18300'],
            ['area_code' => 'MYS-03-JL', 'country_code' => 'MYS', 'state_code' => 'MY-03', 'area_name' => 'Jeli', 'area_type' => 'district', 'postal_code' => '17600'],
            // Malaysia: Malacca (MY-04)
            ['area_code' => 'MYS-04-MC', 'country_code' => 'MYS', 'state_code' => 'MY-04', 'area_name' => 'Melaka Tengah', 'area_type' => 'district', 'postal_code' => '75000'],
            ['area_code' => 'MYS-04-AL', 'country_code' => 'MYS', 'state_code' => 'MY-04', 'area_name' => 'Alor Gajah', 'area_type' => 'district', 'postal_code' => '78000'],
            ['area_code' => 'MYS-04-JS', 'country_code' => 'MYS', 'state_code' => 'MY-04', 'area_name' => 'Jasin', 'area_type' => 'district', 'postal_code' => '77000'],
            // Malaysia: Negeri Sembilan (MY-05)
            ['area_code' => 'MYS-05-SP', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Seremban', 'area_type' => 'city', 'postal_code' => '70000'],
            ['area_code' => 'MYS-05-PD', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Port Dickson', 'area_type' => 'district', 'postal_code' => '71000'],
            ['area_code' => 'MYS-05-KP', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Kuala Pilah', 'area_type' => 'district', 'postal_code' => '72000'],
            ['area_code' => 'MYS-05-JP', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Jempol', 'area_type' => 'district', 'postal_code' => '72120'],
            ['area_code' => 'MYS-05-TS', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Tampin', 'area_type' => 'district', 'postal_code' => '73000'],
            ['area_code' => 'MYS-05-JL', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Jelebu', 'area_type' => 'district', 'postal_code' => '71600'],
            ['area_code' => 'MYS-05-RB', 'country_code' => 'MYS', 'state_code' => 'MY-05', 'area_name' => 'Rembau', 'area_type' => 'district', 'postal_code' => '71300'],
            // Malaysia: Pahang (MY-06)
            ['area_code' => 'MYS-06-KN', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Kuantan', 'area_type' => 'city', 'postal_code' => '25000'],
            ['area_code' => 'MYS-06-TM', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Temerloh', 'area_type' => 'district', 'postal_code' => '28000'],
            ['area_code' => 'MYS-06-RB', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Raub', 'area_type' => 'district', 'postal_code' => '27600'],
            ['area_code' => 'MYS-06-BT', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Bentong', 'area_type' => 'district', 'postal_code' => '28700'],
            ['area_code' => 'MYS-06-LP', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Lipis', 'area_type' => 'district', 'postal_code' => '27200'],
            ['area_code' => 'MYS-06-CR', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Cameron Highlands', 'area_type' => 'district', 'postal_code' => '39000'],
            ['area_code' => 'MYS-06-JR', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Jerantut', 'area_type' => 'district', 'postal_code' => '27000'],
            ['area_code' => 'MYS-06-PK', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Pekan', 'area_type' => 'district', 'postal_code' => '26600'],
            ['area_code' => 'MYS-06-MR', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Maran', 'area_type' => 'district', 'postal_code' => '26500'],
            ['area_code' => 'MYS-06-BJ', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Bera', 'area_type' => 'district', 'postal_code' => '28200'],
            ['area_code' => 'MYS-06-RP', 'country_code' => 'MYS', 'state_code' => 'MY-06', 'area_name' => 'Rompin', 'area_type' => 'district', 'postal_code' => '26800'],
            // Malaysia: Penang (MY-07)
            ['area_code' => 'MYS-07-GT', 'country_code' => 'MYS', 'state_code' => 'MY-07', 'area_name' => 'George Town', 'area_type' => 'city', 'postal_code' => '10000'],
            ['area_code' => 'MYS-07-TM', 'country_code' => 'MYS', 'state_code' => 'MY-07', 'area_name' => 'Timur Laut', 'area_type' => 'district', 'postal_code' => '10300'],
            ['area_code' => 'MYS-07-BS', 'country_code' => 'MYS', 'state_code' => 'MY-07', 'area_name' => 'Barat Daya', 'area_type' => 'district', 'postal_code' => '11000'],
            ['area_code' => 'MYS-07-SU', 'country_code' => 'MYS', 'state_code' => 'MY-07', 'area_name' => 'Seberang Perai Utara', 'area_type' => 'district', 'postal_code' => '12000'],
            ['area_code' => 'MYS-07-ST', 'country_code' => 'MYS', 'state_code' => 'MY-07', 'area_name' => 'Seberang Perai Tengah', 'area_type' => 'district', 'postal_code' => '13000'],
            ['area_code' => 'MYS-07-SS', 'country_code' => 'MYS', 'state_code' => 'MY-07', 'area_name' => 'Seberang Perai Selatan', 'area_type' => 'district', 'postal_code' => '14000'],
            // Malaysia: Perak (MY-08)
            ['area_code' => 'MYS-08-IP', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Ipoh', 'area_type' => 'city', 'postal_code' => '30000'],
            ['area_code' => 'MYS-08-KR', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Kinta', 'area_type' => 'district', 'postal_code' => '31000'],
            ['area_code' => 'MYS-08-LR', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Larut, Matang dan Selama', 'area_type' => 'district', 'postal_code' => '34000'],
            ['area_code' => 'MYS-08-MJ', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Manjung', 'area_type' => 'district', 'postal_code' => '32000'],
            ['area_code' => 'MYS-08-KS', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Kuala Kangsar', 'area_type' => 'district', 'postal_code' => '33000'],
            ['area_code' => 'MYS-08-BT', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Batang Padang', 'area_type' => 'district', 'postal_code' => '35000'],
            ['area_code' => 'MYS-08-HS', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Hilir Perak', 'area_type' => 'district', 'postal_code' => '36000'],
            ['area_code' => 'MYS-08-KP', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Kerian', 'area_type' => 'district', 'postal_code' => '34200'],
            ['area_code' => 'MYS-08-PS', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Perak Tengah', 'area_type' => 'district', 'postal_code' => '32600'],
            ['area_code' => 'MYS-08-KM', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Kampar', 'area_type' => 'district', 'postal_code' => '31900'],
            ['area_code' => 'MYS-08-MK', 'country_code' => 'MYS', 'state_code' => 'MY-08', 'area_name' => 'Muallim', 'area_type' => 'district', 'postal_code' => '35900'],
            // Malaysia: Perlis (MY-09)
            ['area_code' => 'MYS-09-KG', 'country_code' => 'MYS', 'state_code' => 'MY-09', 'area_name' => 'Kangar', 'area_type' => 'district', 'postal_code' => '01000'],
            // Malaysia: Selangor (MY-10)
            ['area_code' => 'MYS-10-PJ', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Petaling Jaya', 'area_type' => 'city', 'postal_code' => '46000'],
            ['area_code' => 'MYS-10-SA', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Shah Alam', 'area_type' => 'city', 'postal_code' => '40000'],
            ['area_code' => 'MYS-10-SJ', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Subang Jaya', 'area_type' => 'city', 'postal_code' => '47500'],
            ['area_code' => 'MYS-10-KG', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Klang', 'area_type' => 'city', 'postal_code' => '41000'],
            ['area_code' => 'MYS-10-GS', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Gombak', 'area_type' => 'district', 'postal_code' => '53100'],
            ['area_code' => 'MYS-10-KS', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Kuala Selangor', 'area_type' => 'district', 'postal_code' => '45000'],
            ['area_code' => 'MYS-10-SB', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Sabak Bernam', 'area_type' => 'district', 'postal_code' => '45200'],
            ['area_code' => 'MYS-10-HS', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Hulu Selangor', 'area_type' => 'district', 'postal_code' => '44000'],
            ['area_code' => 'MYS-10-HL', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Hulu Langat', 'area_type' => 'district', 'postal_code' => '43100'],
            ['area_code' => 'MYS-10-KL', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Kuala Langat', 'area_type' => 'district', 'postal_code' => '42700'],
            ['area_code' => 'MYS-10-SP', 'country_code' => 'MYS', 'state_code' => 'MY-10', 'area_name' => 'Sepang', 'area_type' => 'district', 'postal_code' => '43900'],
            // Malaysia: Terengganu (MY-11)
            ['area_code' => 'MYS-11-KT', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Kuala Terengganu', 'area_type' => 'city', 'postal_code' => '20000'],
            ['area_code' => 'MYS-11-BS', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Besut', 'area_type' => 'district', 'postal_code' => '22200'],
            ['area_code' => 'MYS-11-DG', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Dungun', 'area_type' => 'district', 'postal_code' => '23000'],
            ['area_code' => 'MYS-11-KM', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Kemaman', 'area_type' => 'district', 'postal_code' => '24000'],
            ['area_code' => 'MYS-11-MR', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Marang', 'area_type' => 'district', 'postal_code' => '21600'],
            ['area_code' => 'MYS-11-HS', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Hulu Terengganu', 'area_type' => 'district', 'postal_code' => '21700'],
            ['area_code' => 'MYS-11-ST', 'country_code' => 'MYS', 'state_code' => 'MY-11', 'area_name' => 'Setiu', 'area_type' => 'district', 'postal_code' => '22100'],
            // Malaysia: Sabah (MY-12)
            ['area_code' => 'MYS-12-KK', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Kota Kinabalu', 'area_type' => 'city', 'postal_code' => '88000'],
            ['area_code' => 'MYS-12-TW', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Tawau', 'area_type' => 'district', 'postal_code' => '91000'],
            ['area_code' => 'MYS-12-SD', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Sandakan', 'area_type' => 'district', 'postal_code' => '90000'],
            ['area_code' => 'MYS-12-LH', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Lahad Datu', 'area_type' => 'district', 'postal_code' => '91100'],
            ['area_code' => 'MYS-12-KD', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Kudat', 'area_type' => 'district', 'postal_code' => '89050'],
            ['area_code' => 'MYS-12-RN', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Ranau', 'area_type' => 'district', 'postal_code' => '89300'],
            ['area_code' => 'MYS-12-BF', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Beaufort', 'area_type' => 'district', 'postal_code' => '89800'],
            ['area_code' => 'MYS-12-KG', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Keningau', 'area_type' => 'district', 'postal_code' => '89000'],
            ['area_code' => 'MYS-12-TB', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Tambunan', 'area_type' => 'district', 'postal_code' => '89650'],
            ['area_code' => 'MYS-12-TN', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Tenom', 'area_type' => 'district', 'postal_code' => '89900'],
            ['area_code' => 'MYS-12-KM', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Kota Marudu', 'area_type' => 'district', 'postal_code' => '89100'],
            ['area_code' => 'MYS-12-PT', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Pitas', 'area_type' => 'district', 'postal_code' => '89150'],
            ['area_code' => 'MYS-12-KT', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Kota Belud', 'area_type' => 'district', 'postal_code' => '89250'],
            ['area_code' => 'MYS-12-TU', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Tuaran', 'area_type' => 'district', 'postal_code' => '89200'],
            ['area_code' => 'MYS-12-PG', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Penampang', 'area_type' => 'district', 'postal_code' => '89500'],
            ['area_code' => 'MYS-12-PP', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Papar', 'area_type' => 'district', 'postal_code' => '89600'],
            ['area_code' => 'MYS-12-KP', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Kunak', 'area_type' => 'district', 'postal_code' => '91200'],
            ['area_code' => 'MYS-12-SM', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Semporna', 'area_type' => 'district', 'postal_code' => '91300'],
            ['area_code' => 'MYS-12-SB', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Sipitang', 'area_type' => 'district', 'postal_code' => '89850'],
            ['area_code' => 'MYS-12-TG', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Tongod', 'area_type' => 'district', 'postal_code' => '89350'],
            ['area_code' => 'MYS-12-BL', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Beluran', 'area_type' => 'district', 'postal_code' => '90100'],
            ['area_code' => 'MYS-12-TL', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Telupid', 'area_type' => 'district', 'postal_code' => '89320'],
            ['area_code' => 'MYS-12-KN', 'country_code' => 'MYS', 'state_code' => 'MY-12', 'area_name' => 'Kinabatangan', 'area_type' => 'district', 'postal_code' => '90200'],
            // Malaysia: Sarawak (MY-13)
            ['area_code' => 'MYS-13-KC', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Kuching', 'area_type' => 'city', 'postal_code' => '93000'],
            ['area_code' => 'MYS-13-SM', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Samarahan', 'area_type' => 'district', 'postal_code' => '94300'],
            ['area_code' => 'MYS-13-SR', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Serian', 'area_type' => 'district', 'postal_code' => '94700'],
            ['area_code' => 'MYS-13-SB', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Sibu', 'area_type' => 'district', 'postal_code' => '96000'],
            ['area_code' => 'MYS-13-MR', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Miri', 'area_type' => 'district', 'postal_code' => '98000'],
            ['area_code' => 'MYS-13-BT', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Bintulu', 'area_type' => 'district', 'postal_code' => '97000'],
            ['area_code' => 'MYS-13-KP', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Kapit', 'area_type' => 'district', 'postal_code' => '96800'],
            ['area_code' => 'MYS-13-SK', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Sarikei', 'area_type' => 'district', 'postal_code' => '96100'],
            ['area_code' => 'MYS-13-BK', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Betong', 'area_type' => 'district', 'postal_code' => '95700'],
            ['area_code' => 'MYS-13-LB', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Limbang', 'area_type' => 'district', 'postal_code' => '98700'],
            ['area_code' => 'MYS-13-SG', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Sri Aman', 'area_type' => 'district', 'postal_code' => '95000'],
            ['area_code' => 'MYS-13-MK', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Mukah', 'area_type' => 'district', 'postal_code' => '96400'],
            ['area_code' => 'MYS-13-DL', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Daro', 'area_type' => 'district', 'postal_code' => '96200'],
            ['area_code' => 'MYS-13-MT', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Matu', 'area_type' => 'district', 'postal_code' => '96250'],
            ['area_code' => 'MYS-13-LW', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Lawas', 'area_type' => 'district', 'postal_code' => '98850'],
            ['area_code' => 'MYS-13-KN', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Kanowit', 'area_type' => 'district', 'postal_code' => '96700'],
            ['area_code' => 'MYS-13-SO', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Song', 'area_type' => 'district', 'postal_code' => '96850'],
            ['area_code' => 'MYS-13-BL', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Belaga', 'area_type' => 'district', 'postal_code' => '96900'],
            ['area_code' => 'MYS-13-MD', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Marudi', 'area_type' => 'district', 'postal_code' => '98050'],
            ['area_code' => 'MYS-13-LG', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Lubok Antu', 'area_type' => 'district', 'postal_code' => '95800'],
            ['area_code' => 'MYS-13-TT', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Tatau', 'area_type' => 'district', 'postal_code' => '97200'],
            ['area_code' => 'MYS-13-SL', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Selangau', 'area_type' => 'district', 'postal_code' => '96050'],
            ['area_code' => 'MYS-13-PK', 'country_code' => 'MYS', 'state_code' => 'MY-13', 'area_name' => 'Pakan', 'area_type' => 'district', 'postal_code' => '96510'],
            // Malaysia: Kuala Lumpur (MY-14)
            ['area_code' => 'MYS-14-KL', 'country_code' => 'MYS', 'state_code' => 'MY-14', 'area_name' => 'Kuala Lumpur', 'area_type' => 'city', 'postal_code' => '50000'],
            // Malaysia: Labuan (MY-15)
            ['area_code' => 'MYS-15-LB', 'country_code' => 'MYS', 'state_code' => 'MY-15', 'area_name' => 'Labuan', 'area_type' => 'city', 'postal_code' => '87000'],
            // Malaysia: Putrajaya (MY-16)
            ['area_code' => 'MYS-16-PJ', 'country_code' => 'MYS', 'state_code' => 'MY-16', 'area_name' => 'Putrajaya', 'area_type' => 'city', 'postal_code' => '62000'],
            // Singapore: Singapore (SG-SG)
            ['area_code' => 'SGP-SG-AM', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Ang Mo Kio', 'area_type' => 'Planning Area', 'postal_code' => '569830'],
            ['area_code' => 'SGP-SG-BD', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Bedok', 'area_type' => 'Planning Area', 'postal_code' => '469560'],
            ['area_code' => 'SGP-SG-BB', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Bukit Batok', 'area_type' => 'Planning Area', 'postal_code' => '659578'],
            ['area_code' => 'SGP-SG-BM', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Bukit Merah', 'area_type' => 'Planning Area', 'postal_code' => '159836'],
            ['area_code' => 'SGP-SG-BP', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Bukit Panjang', 'area_type' => 'Planning Area', 'postal_code' => '679944'],
            ['area_code' => 'SGP-SG-BT', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Bukit Timah', 'area_type' => 'Planning Area', 'postal_code' => '279621'],
            ['area_code' => 'SGP-SG-CC', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Central Area', 'area_type' => 'Planning Area', 'postal_code' => '179431'],
            ['area_code' => 'SGP-SG-CK', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Choa Chu Kang', 'area_type' => 'Planning Area', 'postal_code' => '689810'],
            ['area_code' => 'SGP-SG-CL', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Clementi', 'area_type' => 'Planning Area', 'postal_code' => '129588'],
            ['area_code' => 'SGP-SG-GY', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Geylang', 'area_type' => 'Planning Area', 'postal_code' => '389708'],
            ['area_code' => 'SGP-SG-HG', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Hougang', 'area_type' => 'Planning Area', 'postal_code' => '530558'],
            ['area_code' => 'SGP-SG-JW', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Jurong West', 'area_type' => 'Planning Area', 'postal_code' => '649846'],
            ['area_code' => 'SGP-SG-JE', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Jurong East', 'area_type' => 'Planning Area', 'postal_code' => '609690'],
            ['area_code' => 'SGP-SG-KB', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Kallang', 'area_type' => 'Planning Area', 'postal_code' => '339696'],
            ['area_code' => 'SGP-SG-MP', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Marine Parade', 'area_type' => 'Planning Area', 'postal_code' => '449269'],
            ['area_code' => 'SGP-SG-NV', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Novena', 'area_type' => 'Planning Area', 'postal_code' => '307987'],
            ['area_code' => 'SGP-SG-PS', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Pasir Ris', 'area_type' => 'Planning Area', 'postal_code' => '519641'],
            ['area_code' => 'SGP-SG-PG', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Punggol', 'area_type' => 'Planning Area', 'postal_code' => '828761'],
            ['area_code' => 'SGP-SG-QT', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Queenstown', 'area_type' => 'Planning Area', 'postal_code' => '149053'],
            ['area_code' => 'SGP-SG-SB', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Sembawang', 'area_type' => 'Planning Area', 'postal_code' => '757618'],
            ['area_code' => 'SGP-SG-SG', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Sengkang', 'area_type' => 'Planning Area', 'postal_code' => '545025'],
            ['area_code' => 'SGP-SG-SR', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Serangoon', 'area_type' => 'Planning Area', 'postal_code' => '550535'],
            ['area_code' => 'SGP-SG-TB', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Tampines', 'area_type' => 'Planning Area', 'postal_code' => '529284'],
            ['area_code' => 'SGP-SG-TG', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Tanglin', 'area_type' => 'Planning Area', 'postal_code' => '247909'],
            ['area_code' => 'SGP-SG-TP', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Toa Payoh', 'area_type' => 'Planning Area', 'postal_code' => '319075'],
            ['area_code' => 'SGP-SG-WL', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Woodlands', 'area_type' => 'Planning Area', 'postal_code' => '738547'],
            ['area_code' => 'SGP-SG-YS', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Yishun', 'area_type' => 'Planning Area', 'postal_code' => '768925'],
            ['area_code' => 'SGP-SG-BS', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Bishan', 'area_type' => 'Planning Area', 'postal_code' => '579778'],
            ['area_code' => 'SGP-SG-TN', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Tengah', 'area_type' => 'Planning Area', 'postal_code' => '698837'],
            ['area_code' => 'SGP-SG-RC', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Rochor', 'area_type' => 'Planning Area', 'postal_code' => '188425'],
            ['area_code' => 'SGP-SG-OU', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Outram', 'area_type' => 'Planning Area', 'postal_code' => '169074'],
            ['area_code' => 'SGP-SG-RV', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'River Valley', 'area_type' => 'Planning Area', 'postal_code' => '238360'],
            ['area_code' => 'SGP-SG-SW', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Seletar', 'area_type' => 'Planning Area', 'postal_code' => '797697'],
            ['area_code' => 'SGP-SG-SN', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Sungei Kadut', 'area_type' => 'Planning Area', 'postal_code' => '729232'],
            ['area_code' => 'SGP-SG-TS', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Tuas', 'area_type' => 'Planning Area', 'postal_code' => '636921'],
            ['area_code' => 'SGP-SG-WI', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Western Islands', 'area_type' => 'Planning Area', 'postal_code' => '627833'],
            ['area_code' => 'SGP-SG-CH', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Changi', 'area_type' => 'Planning Area', 'postal_code' => '498741'],
            ['area_code' => 'SGP-SG-CB', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Changi Bay', 'area_type' => 'Planning Area', 'postal_code' => '509663'],
            ['area_code' => 'SGP-SG-LM', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Lim Chu Kang', 'area_type' => 'Planning Area', 'postal_code' => '719529'],
            ['area_code' => 'SGP-SG-MD', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Mandai', 'area_type' => 'Planning Area', 'postal_code' => '729826'],
            ['area_code' => 'SGP-SG-NE', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'North-Eastern Islands', 'area_type' => 'Planning Area', 'postal_code' => '508487'],
            ['area_code' => 'SGP-SG-PC', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Paya Lebar', 'area_type' => 'Planning Area', 'postal_code' => '408533'],
            ['area_code' => 'SGP-SG-PN', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Pioneer', 'area_type' => 'Planning Area', 'postal_code' => '628509'],
            ['area_code' => 'SGP-SG-BN', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Boon Lay', 'area_type' => 'Planning Area', 'postal_code' => '649846'],
            ['area_code' => 'SGP-SG-DT', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Downtown Core', 'area_type' => 'Planning Area', 'postal_code' => '039594'],
            ['area_code' => 'SGP-SG-MR', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Marina South', 'area_type' => 'Planning Area', 'postal_code' => '018986'],
            ['area_code' => 'SGP-SG-MS', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Museum', 'area_type' => 'Planning Area', 'postal_code' => '178555'],
            ['area_code' => 'SGP-SG-NR', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Newton', 'area_type' => 'Planning Area', 'postal_code' => '229495'],
            ['area_code' => 'SGP-SG-OR', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Orchard', 'area_type' => 'Planning Area', 'postal_code' => '238801'],
            ['area_code' => 'SGP-SG-SK', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Singapore River', 'area_type' => 'Planning Area', 'postal_code' => '058282'],
            ['area_code' => 'SGP-SG-ST', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Straits View', 'area_type' => 'Planning Area', 'postal_code' => '018937'],
            ['area_code' => 'SGP-SG-WW', 'country_code' => 'SGP', 'state_code' => 'SG-SG', 'area_name' => 'Western Water Catchment', 'area_type' => 'Planning Area', 'postal_code' => '708976'],
        ];

        // Insert areas in batches to optimize performance
        $chunks = array_chunk($areas, 100); // Smaller chunk size for Malaysia and Singapore
        foreach ($chunks as $chunk) {
            DB::table('tbl_areas')->insert(array_map(function ($area) {
                return [
                    'area_code' => $area['area_code'],
                    'country_code' => $area['country_code'],
                    'state_code' => $area['state_code'],
                    'area_name' => $area['area_name'],
                    'area_type' => $area['area_type'],
                    'postal_code' => $area['postal_code'],
                    'status' => 1,
                    'delete' => 0,
                    'created_on' => now(),
                    'updated_on' => now(),
                ];
            }, $chunk));
        }
    }
}
