<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bank;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            [
                'bank_name' => 'Maybank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'CIMB',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Public Bank Berhad',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'RHB',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Hong Leong',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'AmBank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Affin',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Alliance',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Bank Islam',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Bank Muamalat',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'HSBC',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Standard Chartered',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'OCBC Bank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Bank Rakyat',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Bank Simpanan Nasional (BSN)',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'GXBank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'AEON Bank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'DBS Bank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'United Overseas Bank (UOB)',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Bank of Singapore',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'GXS Bank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'MariBank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Trust Bank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Citibank',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'Bank of China',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
            [
                'bank_name' => 'State Bank of India',
                'icon' => null,
                'api' => null,
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ],
        ];
        DB::table('tbl_bank')->insert($banks);
    }
}
