<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Countries;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_code' => 'AFG', 'country_name' => 'Afghanistan'],
            ['country_code' => 'ALA', 'country_name' => 'Åland Islands'],
            ['country_code' => 'ALB', 'country_name' => 'Albania'],
            ['country_code' => 'DZA', 'country_name' => 'Algeria'],
            ['country_code' => 'ASM', 'country_name' => 'American Samoa'],
            ['country_code' => 'AND', 'country_name' => 'Andorra'],
            ['country_code' => 'AGO', 'country_name' => 'Angola'],
            ['country_code' => 'AIA', 'country_name' => 'Anguilla'],
            ['country_code' => 'ATA', 'country_name' => 'Antarctica'],
            ['country_code' => 'ATG', 'country_name' => 'Antigua and Barbuda'],
            ['country_code' => 'ARG', 'country_name' => 'Argentina'],
            ['country_code' => 'ARM', 'country_name' => 'Armenia'],
            ['country_code' => 'ABW', 'country_name' => 'Aruba'],
            ['country_code' => 'AUS', 'country_name' => 'Australia'],
            ['country_code' => 'AUT', 'country_name' => 'Austria'],
            ['country_code' => 'AZE', 'country_name' => 'Azerbaijan'],
            ['country_code' => 'BHS', 'country_name' => 'Bahamas'],
            ['country_code' => 'BHR', 'country_name' => 'Bahrain'],
            ['country_code' => 'BGD', 'country_name' => 'Bangladesh'],
            ['country_code' => 'BRB', 'country_name' => 'Barbados'],
            ['country_code' => 'BLR', 'country_name' => 'Belarus'],
            ['country_code' => 'BEL', 'country_name' => 'Belgium'],
            ['country_code' => 'BLZ', 'country_name' => 'Belize'],
            ['country_code' => 'BEN', 'country_name' => 'Benin'],
            ['country_code' => 'BMU', 'country_name' => 'Bermuda'],
            ['country_code' => 'BTN', 'country_name' => 'Bhutan'],
            ['country_code' => 'BOL', 'country_name' => 'Bolivia'],
            ['country_code' => 'BES', 'country_name' => 'Bonaire, Sint Eustatius and Saba'],
            ['country_code' => 'BIH', 'country_name' => 'Bosnia and Herzegovina'],
            ['country_code' => 'BWA', 'country_name' => 'Botswana'],
            ['country_code' => 'BVT', 'country_name' => 'Bouvet Island'],
            ['country_code' => 'BRA', 'country_name' => 'Brazil'],
            ['country_code' => 'IOT', 'country_name' => 'British Indian Ocean Territory'],
            ['country_code' => 'BRN', 'country_name' => 'Brunei Darussalam'],
            ['country_code' => 'BGR', 'country_name' => 'Bulgaria'],
            ['country_code' => 'BFA', 'country_name' => 'Burkina Faso'],
            ['country_code' => 'BDI', 'country_name' => 'Burundi'],
            ['country_code' => 'CPV', 'country_name' => 'Cabo Verde'],
            ['country_code' => 'KHM', 'country_name' => 'Cambodia'],
            ['country_code' => 'CMR', 'country_name' => 'Cameroon'],
            ['country_code' => 'CAN', 'country_name' => 'Canada'],
            ['country_code' => 'CYM', 'country_name' => 'Cayman Islands'],
            ['country_code' => 'CAF', 'country_name' => 'Central African Republic'],
            ['country_code' => 'TCD', 'country_name' => 'Chad'],
            ['country_code' => 'CHL', 'country_name' => 'Chile'],
            ['country_code' => 'CHN', 'country_name' => 'China'],
            ['country_code' => 'CXR', 'country_name' => 'Christmas Island'],
            ['country_code' => 'CCK', 'country_name' => 'Cocos (Keeling) Islands'],
            ['country_code' => 'COL', 'country_name' => 'Colombia'],
            ['country_code' => 'COM', 'country_name' => 'Comoros'],
            ['country_code' => 'COG', 'country_name' => 'Congo'],
            ['country_code' => 'COD', 'country_name' => 'Congo, Democratic Republic of the'],
            ['country_code' => 'COK', 'country_name' => 'Cook Islands'],
            ['country_code' => 'CRI', 'country_name' => 'Costa Rica'],
            ['country_code' => 'CIV', 'country_name' => 'Côte d\'Ivoire'],
            ['country_code' => 'HRV', 'country_name' => 'Croatia'],
            ['country_code' => 'CUB', 'country_name' => 'Cuba'],
            ['country_code' => 'CUW', 'country_name' => 'Curaçao'],
            ['country_code' => 'CYP', 'country_name' => 'Cyprus'],
            ['country_code' => 'CZE', 'country_name' => 'Czechia'],
            ['country_code' => 'DNK', 'country_name' => 'Denmark'],
            ['country_code' => 'DJI', 'country_name' => 'Djibouti'],
            ['country_code' => 'DMA', 'country_name' => 'Dominica'],
            ['country_code' => 'DOM', 'country_name' => 'Dominican Republic'],
            ['country_code' => 'ECU', 'country_name' => 'Ecuador'],
            ['country_code' => 'EGY', 'country_name' => 'Egypt'],
            ['country_code' => 'SLV', 'country_name' => 'El Salvador'],
            ['country_code' => 'GNQ', 'country_name' => 'Equatorial Guinea'],
            ['country_code' => 'ERI', 'country_name' => 'Eritrea'],
            ['country_code' => 'EST', 'country_name' => 'Estonia'],
            ['country_code' => 'SWZ', 'country_name' => 'Eswatini'],
            ['country_code' => 'ETH', 'country_name' => 'Ethiopia'],
            ['country_code' => 'FLK', 'country_name' => 'Falkland Islands (Malvinas)'],
            ['country_code' => 'FRO', 'country_name' => 'Faroe Islands'],
            ['country_code' => 'FJI', 'country_name' => 'Fiji'],
            ['country_code' => 'FIN', 'country_name' => 'Finland'],
            ['country_code' => 'FRA', 'country_name' => 'France'],
            ['country_code' => 'GUF', 'country_name' => 'French Guiana'],
            ['country_code' => 'PYF', 'country_name' => 'French Polynesia'],
            ['country_code' => 'ATF', 'country_name' => 'French Southern Territories'],
            ['country_code' => 'GAB', 'country_name' => 'Gabon'],
            ['country_code' => 'GMB', 'country_name' => 'Gambia'],
            ['country_code' => 'GEO', 'country_name' => 'Georgia'],
            ['country_code' => 'DEU', 'country_name' => 'Germany'],
            ['country_code' => 'GHA', 'country_name' => 'Ghana'],
            ['country_code' => 'GIB', 'country_name' => 'Gibraltar'],
            ['country_code' => 'GRC', 'country_name' => 'Greece'],
            ['country_code' => 'GRL', 'country_name' => 'Greenland'],
            ['country_code' => 'GRD', 'country_name' => 'Grenada'],
            ['country_code' => 'GLP', 'country_name' => 'Guadeloupe'],
            ['country_code' => 'GUM', 'country_name' => 'Guam'],
            ['country_code' => 'GTM', 'country_name' => 'Guatemala'],
            ['country_code' => 'GGY', 'country_name' => 'Guernsey'],
            ['country_code' => 'GIN', 'country_name' => 'Guinea'],
            ['country_code' => 'GNB', 'country_name' => 'Guinea-Bissau'],
            ['country_code' => 'GUY', 'country_name' => 'Guyana'],
            ['country_code' => 'HTI', 'country_name' => 'Haiti'],
            ['country_code' => 'HMD', 'country_name' => 'Heard Island and McDonald Islands'],
            ['country_code' => 'VAT', 'country_name' => 'Holy See'],
            ['country_code' => 'HND', 'country_name' => 'Honduras'],
            ['country_code' => 'HKG', 'country_name' => 'Hong Kong'],
            ['country_code' => 'HUN', 'country_name' => 'Hungary'],
            ['country_code' => 'ISL', 'country_name' => 'Iceland'],
            ['country_code' => 'IND', 'country_name' => 'India'],
            ['country_code' => 'IDN', 'country_name' => 'Indonesia'],
            ['country_code' => 'IRN', 'country_name' => 'Iran, Islamic Republic of'],
            ['country_code' => 'IRQ', 'country_name' => 'Iraq'],
            ['country_code' => 'IRL', 'country_name' => 'Ireland'],
            ['country_code' => 'IMN', 'country_name' => 'Isle of Man'],
            ['country_code' => 'ISR', 'country_name' => 'Israel'],
            ['country_code' => 'ITA', 'country_name' => 'Italy'],
            ['country_code' => 'JAM', 'country_name' => 'Jamaica'],
            ['country_code' => 'JPN', 'country_name' => 'Japan'],
            ['country_code' => 'JEY', 'country_name' => 'Jersey'],
            ['country_code' => 'JOR', 'country_name' => 'Jordan'],
            ['country_code' => 'KAZ', 'country_name' => 'Kazakhstan'],
            ['country_code' => 'KEN', 'country_name' => 'Kenya'],
            ['country_code' => 'KIR', 'country_name' => 'Kiribati'],
            ['country_code' => 'PRK', 'country_name' => 'Korea, Democratic People\'s Republic of'],
            ['country_code' => 'KOR', 'country_name' => 'Korea, Republic of'],
            ['country_code' => 'KWT', 'country_name' => 'Kuwait'],
            ['country_code' => 'KGZ', 'country_name' => 'Kyrgyzstan'],
            ['country_code' => 'LAO', 'country_name' => 'Lao People\'s Democratic Republic'],
            ['country_code' => 'LVA', 'country_name' => 'Latvia'],
            ['country_code' => 'LBN', 'country_name' => 'Lebanon'],
            ['country_code' => 'LSO', 'country_name' => 'Lesotho'],
            ['country_code' => 'LBR', 'country_name' => 'Liberia'],
            ['country_code' => 'LBY', 'country_name' => 'Libya'],
            ['country_code' => 'LIE', 'country_name' => 'Liechtenstein'],
            ['country_code' => 'LTU', 'country_name' => 'Lithuania'],
            ['country_code' => 'LUX', 'country_name' => 'Luxembourg'],
            ['country_code' => 'MAC', 'country_name' => 'Macao'],
            ['country_code' => 'MDG', 'country_name' => 'Madagascar'],
            ['country_code' => 'MWI', 'country_name' => 'Malawi'],
            ['country_code' => 'MYS', 'country_name' => 'Malaysia'],
            ['country_code' => 'MDV', 'country_name' => 'Maldives'],
            ['country_code' => 'MLI', 'country_name' => 'Mali'],
            ['country_code' => 'MLT', 'country_name' => 'Malta'],
            ['country_code' => 'MHL', 'country_name' => 'Marshall Islands'],
            ['country_code' => 'MTQ', 'country_name' => 'Martinique'],
            ['country_code' => 'MRT', 'country_name' => 'Mauritania'],
            ['country_code' => 'MUS', 'country_name' => 'Mauritius'],
            ['country_code' => 'MYT', 'country_name' => 'Mayotte'],
            ['country_code' => 'MEX', 'country_name' => 'Mexico'],
            ['country_code' => 'FSM', 'country_name' => 'Micronesia, Federated States of'],
            ['country_code' => 'MDA', 'country_name' => 'Moldova, Republic of'],
            ['country_code' => 'MCO', 'country_name' => 'Monaco'],
            ['country_code' => 'MNG', 'country_name' => 'Mongolia'],
            ['country_code' => 'MNE', 'country_name' => 'Montenegro'],
            ['country_code' => 'MSR', 'country_name' => 'Montserrat'],
            ['country_code' => 'MAR', 'country_name' => 'Morocco'],
            ['country_code' => 'MOZ', 'country_name' => 'Mozambique'],
            ['country_code' => 'MMR', 'country_name' => 'Myanmar'],
            ['country_code' => 'NAM', 'country_name' => 'Namibia'],
            ['country_code' => 'NRU', 'country_name' => 'Nauru'],
            ['country_code' => 'NPL', 'country_name' => 'Nepal'],
            ['country_code' => 'NLD', 'country_name' => 'Netherlands'],
            ['country_code' => 'NCL', 'country_name' => 'New Caledonia'],
            ['country_code' => 'NZL', 'country_name' => 'New Zealand'],
            ['country_code' => 'NIC', 'country_name' => 'Nicaragua'],
            ['country_code' => 'NER', 'country_name' => 'Niger'],
            ['country_code' => 'NGA', 'country_name' => 'Nigeria'],
            ['country_code' => 'NIU', 'country_name' => 'Niue'],
            ['country_code' => 'NFK', 'country_name' => 'Norfolk Island'],
            ['country_code' => 'MKD', 'country_name' => 'North Macedonia'],
            ['country_code' => 'MNP', 'country_name' => 'Northern Mariana Islands'],
            ['country_code' => 'NOR', 'country_name' => 'Norway'],
            ['country_code' => 'OMN', 'country_name' => 'Oman'],
            ['country_code' => 'PAK', 'country_name' => 'Pakistan'],
            ['country_code' => 'PLW', 'country_name' => 'Palau'],
            ['country_code' => 'PSE', 'country_name' => 'Palestine, State of'],
            ['country_code' => 'PAN', 'country_name' => 'Panama'],
            ['country_code' => 'PNG', 'country_name' => 'Papua New Guinea'],
            ['country_code' => 'PRY', 'country_name' => 'Paraguay'],
            ['country_code' => 'PER', 'country_name' => 'Peru'],
            ['country_code' => 'PHL', 'country_name' => 'Philippines'],
            ['country_code' => 'PCN', 'country_name' => 'Pitcairn'],
            ['country_code' => 'POL', 'country_name' => 'Poland'],
            ['country_code' => 'PRT', 'country_name' => 'Portugal'],
            ['country_code' => 'PRI', 'country_name' => 'Puerto Rico'],
            ['country_code' => 'QAT', 'country_name' => 'Qatar'],
            ['country_code' => 'REU', 'country_name' => 'Réunion'],
            ['country_code' => 'ROU', 'country_name' => 'Romania'],
            ['country_code' => 'RUS', 'country_name' => 'Russian Federation'],
            ['country_code' => 'RWA', 'country_name' => 'Rwanda'],
            ['country_code' => 'BLM', 'country_name' => 'Saint Barthélemy'],
            ['country_code' => 'SHN', 'country_name' => 'Saint Helena, Ascension and Tristan da Cunha'],
            ['country_code' => 'KNA', 'country_name' => 'Saint Kitts and Nevis'],
            ['country_code' => 'LCA', 'country_name' => 'Saint Lucia'],
            ['country_code' => 'MAF', 'country_name' => 'Saint Martin (French part)'],
            ['country_code' => 'SPM', 'country_name' => 'Saint Pierre and Miquelon'],
            ['country_code' => 'VCT', 'country_name' => 'Saint Vincent and the Grenadines'],
            ['country_code' => 'WSM', 'country_name' => 'Samoa'],
            ['country_code' => 'SMR', 'country_name' => 'San Marino'],
            ['country_code' => 'STP', 'country_name' => 'Sao Tome and PrincipeLex'],
            ['country_code' => 'SAU', 'country_name' => 'Saudi Arabia'],
            ['country_code' => 'SEN', 'country_name' => 'Senegal'],
            ['country_code' => 'SRB', 'country_name' => 'Serbia'],
            ['country_code' => 'SYC', 'country_name' => 'Seychelles'],
            ['country_code' => 'SLE', 'country_name' => 'Sierra Leone'],
            ['country_code' => 'SGP', 'country_name' => 'Singapore'],
            ['country_code' => 'SXM', 'country_name' => 'Sint Maarten (Dutch part)'],
            ['country_code' => 'SVK', 'country_name' => 'Slovakia'],
            ['country_code' => 'SVN', 'country_name' => 'Slovenia'],
            ['country_code' => 'SLB', 'country_name' => 'Solomon Islands'],
            ['country_code' => 'SOM', 'country_name' => 'Somalia'],
            ['country_code' => 'ZAF', 'country_name' => 'South Africa'],
            ['country_code' => 'SGS', 'country_name' => 'South Georgia and the South Sandwich Islands'],
            ['country_code' => 'SSD', 'country_name' => 'South Sudan'],
            ['country_code' => 'ESP', 'country_name' => 'Spain'],
            ['country_code' => 'LKA', 'country_name' => 'Sri Lanka'],
            ['country_code' => 'SDN', 'country_name' => 'Sudan'],
            ['country_code' => 'SUR', 'country_name' => 'Suriname'],
            ['country_code' => 'SJM', 'country_name' => 'Svalbard and Jan Mayen'],
            ['country_code' => 'SWE', 'country_name' => 'Sweden'],
            ['country_code' => 'CHE', 'country_name' => 'Switzerland'],
            ['country_code' => 'SYR', 'country_name' => 'Syrian Arab Republic'],
            ['country_code' => 'TWN', 'country_name' => 'Taiwan'],
            ['country_code' => 'TJK', 'country_name' => 'Tajikistan'],
            ['country_code' => 'TZA', 'country_name' => 'Tanzania, United Republic of'],
            ['country_code' => 'THA', 'country_name' => 'Thailand'],
            ['country_code' => 'TLS', 'country_name' => 'Timor-Leste'],
            ['country_code' => 'TGO', 'country_name' => 'Togo'],
            ['country_code' => 'TKL', 'country_name' => 'Tokelau'],
            ['country_code' => 'TON', 'country_name' => 'Tonga'],
            ['country_code' => 'TTO', 'country_name' => 'Trinidad and Tobago'],
            ['country_code' => 'TUN', 'country_name' => 'Tunisia'],
            ['country_code' => 'TUR', 'country_name' => 'Türkiye'],
            ['country_code' => 'TKM', 'country_name' => 'Turkmenistan'],
            ['country_code' => 'TCA', 'country_name' => 'Turks and Caicos Islands'],
            ['country_code' => 'TUV', 'country_name' => 'Tuvalu'],
            ['country_code' => 'UGA', 'country_name' => 'Uganda'],
            ['country_code' => 'UKR', 'country_name' => 'Ukraine'],
            ['country_code' => 'ARE', 'country_name' => 'United Arab Emirates'],
            ['country_code' => 'GBR', 'country_name' => 'United Kingdom'],
            ['country_code' => 'USA', 'country_name' => 'United States'],
            ['country_code' => 'UMI', 'country_name' => 'United States Minor Outlying Islands'],
            ['country_code' => 'URY', 'country_name' => 'Uruguay'],
            ['country_code' => 'UZB', 'country_name' => 'Uzbekistan'],
            ['country_code' => 'VUT', 'country_name' => 'Vanuatu'],
            ['country_code' => 'VEN', 'country_name' => 'Venezuela, Bolivarian Republic of'],
            ['country_code' => 'VNM', 'country_name' => 'Viet Nam'],
            ['country_code' => 'VGB', 'country_name' => 'Virgin Islands, British'],
            ['country_code' => 'VIR', 'country_name' => 'Virgin Islands, U.S.'],
            ['country_code' => 'WLF', 'country_name' => 'Wallis and Futuna'],
            ['country_code' => 'ESH', 'country_name' => 'Western Sahara'],
            ['country_code' => 'YEM', 'country_name' => 'Yemen'],
            ['country_code' => 'ZMB', 'country_name' => 'Zambia'],
            ['country_code' => 'ZWE', 'country_name' => 'Zimbabwe'],
        ];

        foreach ($countries as $country) {
            DB::table('tbl_countries')->insert([
                'country_code' => $country['country_code'],
                'country_name' => $country['country_name'],
                'status' => 1,
                'delete' => 0,
                'created_on' => now(),
                'updated_on' => now(),
            ]);
        }
    }

}
