export const API_ENDPOINTS = {
  bannerLists: "banner/lists",
  comicIndexLists: "comic/indexLists",
  comicTicai: "comic/ticai",
  comicTags: "comic/tags",
  comicLists: "comic/lists",
  comicRank: "comic/rank",
  comicRanks: "comic/allRank",
  comicGuess: "comic/guess",
  comicInfo: "comic/info",
  comicChapterInfo: "comic/chapterInfo",
  comicSubscribe: "comic/subscribe",
  comicUnsubscribe: "comic/unsubscribe",
  comicFavorite: "comic/favorite",
  comicUnfavorite: "comic/unfavorite",
  comicSearch: "comic/search",
  comicCheckChaptersStatus: "comic/checkChaptersStatus",
  comicChapterBuy: "comic/chapterBuy",
  comicHomepage: "comic/homepage",

  rechargeLists: "recharge/lists",
  rechargePlatforms: "recharge/platforms",
  userInfo: "user/info",
  userLogin: "user/login",
  userRegister: "user/register",
  userSubscribe: "user/subscribe",
  userHistory: "user/history",
  userChangeInfo: "user/changeInfo",
  userRedeemCode: "user/redeemCode",
  userFavorite: "user/favorite",
  userOrderList: "user/orderList",
  userChapterList: "user/record",
  userAutoBuy: "user/autoBuy",
  userChangePassword: "user/changepassword",
  userClearHistory: "user/clearHistory",
  userAddHistory: "user/addHistory",
  userFeedback: "user/feedback",

  adsLists: "ads/lists",
  rechargePay: "recharge/pay",

  config: "config/lists",
  notice: "index/notice",

  // For Comic Statistics Api
  statisticsVisit: "api/visit",
  statisticsLogin: "api/login",
  statisticsRegister: "api/register",
  statisticsRecharge: "api/recharge",
};
