// AUTO-GENERATED — do NOT edit by hand
export const IMAGES = {
  appdownload: {
    android: "/images/appdownload/android.webp",
    apple: "/images/appdownload/apple.webp",
    qr: "/images/appdownload/qr.webp",
  },
  arrowLeft: "/images/arrow-left.webp",
  avatarPlaceholder: "/images/avatar_placeholder.webp",
  bank: {
    affin: "/images/bank/affin.webp",
    ambank: "/images/bank/ambank.webp",
    hongleong: "/images/bank/hongleong.webp",
    hsbc: "/images/bank/hsbc.webp",
    maybank: "/images/bank/maybank.webp",
    muamalat: "/images/bank/muamalat.webp",
    public: "/images/bank/public.webp",
    rhb: "/images/bank/rhb.webp",
  },
  discount: {
    badge: "/images/discount/badge.webp",
    deposit: "/images/discount/deposit.webp",
    refreshCircle: "/images/discount/refresh-circle.webp",
    voucher1: "/images/discount/voucher1.webp",
    voucher2: "/images/discount/voucher2.webp",
    voucher3: "/images/discount/voucher3.webp",
    voucher4: "/images/discount/voucher4.webp",
  },
  earn: {
    arrowup: "/images/earn/arrowup.webp",
    avatar: "/images/earn/avatar.webp",
    avatarA: "/images/earn/avatar-agent.webp",
    iconA: "/images/earn/icon-a.webp",
    diagram: "/images/earn/diagram.webp",
    iconFb: "/images/earn/icon-fb.webp",
    iconGroupEarn: "/images/earn/icon-group-earn.webp",
    iconN: "/images/earn/icon-n.webp",
    iconTelegram: "/images/earn/icon-telegram.webp",
    iconWatapps: "/images/earn/icon-watapps.webp",
    iconWechat: "/images/earn/icon-wechat.webp",
    level: "/images/earn/level.webp",
    qr: "/images/earn/qr.webp",
  },
  empty: "/images/empty.webp",
  favorite: "/images/favorite.webp",
  footer: {
    avatar: "/images/footer/avatar.webp",
    gift: "/images/footer/gift.webp",
    headphone: "/images/footer/headphone.webp",
    home: "/images/footer/home.webp",
  },
  games: {
    banner: "/images/games/banner.webp",
    banner2: "/images/games/banner2.webp",
    iconStar: "/images/games/icon-star.webp",
    iconTransfer: "/images/games/icon-transfer.webp",
    tranferArrowLeft: "/images/games/tranfer_arrow_left.webp",
    transferArrowRight: "/images/games/transfer_arrow_right.webp",
  },
  help: {
    avatar: "/images/help/avatar.webp",
    iconFb: "/images/help/icon-fb.webp",
    iconTelegram: "/images/help/icon-telegram.webp",
    iconWatapps: "/images/help/icon-watapps.webp",
    iconWechat: "/images/help/icon-wechat.webp",
  },
  home: {
    banner: {
      banner1: "/images/home/banner/banner1.webp",
      banner2: "/images/home/banner/banner2.webp",
      word: "/images/home/banner/word.webp",
    },
    profile: {
      currency: "/images/home/profile/currency_exchange.webp",
      bank: "/images/home/profile/bank.webp",
      bluebar: "/images/home/profile/bluebar.webp",
      discout: "/images/home/profile/discout.webp",
      frameRefresh: "/images/home/profile/frame-refresh.webp",
      frameWallet: "/images/home/profile/frame-wallet.webp",
      frame2: "/images/home/profile/frame2.webp",

      p1: "/images/home/profile/bg_top_40.png",
      p2: "/images/home/profile/bg_mid_40.png",
      p3: "/images/home/profile/bg_bottom_40.png",
      p4: "/images/home/profile/bg_bottom_20.png",

      level: "/images/home/profile/level.webp",
      promote: "/images/home/profile/promote.webp",
      topup: "/images/home/profile/topup.webp",
      transaction: "/images/home/profile/transaction.webp",
      vip: "/images/home/profile/vip.webp",
      wallet: "/images/home/profile/wallet.webp",
      withdrawal: "/images/home/profile/withdrawal.webp",

      bank2: "/images/home/profile/icon-bank2.webp",
      event2: "/images/home/profile/icon-event2.webp",
      promo2: "/images/home/profile/icon-promo2.webp",
      topup2: "/images/home/profile/icon-topup2.webp",
      transaction2: "/images/home/profile/icon-trans2.webp",
      vip2: "/images/home/profile/icon-vip2.webp",
      wallet2: "/images/home/profile/icon-wallet2.webp",
      withdrawal2: "/images/home/profile/icon-withdraw2.webp",
    },
    rightbar: {
      provider: "/images/home/rightbar/provider.webp",
      game: "/images/home/rightbar/game.webp",
      game1: "/images/home/rightbar/game1.webp",
      game2: "/images/home/rightbar/game2.webp",
    },
    sidebar: {
      refresh: "/images/home/profile/icon-refresh-yellow.webp",
      bgImage: "/images/home/profile/profilebg.webp",
      bgActive: "/images/home/sidebar/bg-active.webp",
      bgInactiveBlue: "/images/home/sidebar/bg-inactive-blue.webp",
      bgInactive: "/images/home/sidebar/bg-inactive.webp",

      // app
      iconAppInactive: "/images/home/sidebar/icon-app-inactive.webp",
      iconApp: "/images/home/sidebar/icon-app.webp",

      // casino
      iconCasinoInactive: "/images/home/sidebar/icon-casino-inactive.webp",
      iconCasino: "/images/home/sidebar/icon-casino.webp",

      // hot
      iconHotInactive: "/images/home/sidebar/icon-hot-inactive.webp",
      iconHot: "/images/home/sidebar/icon-hot.webp",

      // cockfight
      iconCockfightInactive:
        "/images/home/sidebar/icon-cockfight-inactive.webp",
      iconCockfight: "/images/home/sidebar/icon-cockfight.webp",

      // fishing
      iconFishingInactive: "/images/home/sidebar/icon-fishing-inactive.webp",
      iconFishing: "/images/home/sidebar/icon-fishing.webp",

      // live
      iconLiveInactive: "/images/home/sidebar/icon-live-inactive.webp",
      iconLive: "/images/home/sidebar/icon-live.webp",

      // lottery
      iconLotteryInactive: "/images/home/sidebar/icon-lottery-inactive.webp",
      iconLottery: "/images/home/sidebar/icon-lottery.webp",

      // slot
      iconSlotInactive: "/images/home/sidebar/icon-slot-inactive.webp",
      iconSlot: "/images/home/sidebar/icon-slot.webp",

      // sport
      iconSportInactive: "/images/home/sidebar/icon-sport-inactive.webp",
      iconSport: "/images/home/sidebar/icon-sport.webp",

      // backgrounds
      sidebarBg: "/images/home/sidebar/sidebar-bg.webp",
      sidebarTop: "/images/home/sidebar/sidebar-top.webp",

      iconBitcoinInactive: "/images/home/sidebar/icon-bitcoin-inactive.webp",
      iconBitcoin: "/images/home/sidebar/icon-bitcoin-active.webp",

      iconGraphInactive: "/images/home/sidebar/icon-graph-inactive.webp",
      iconGraph: "/images/home/sidebar/icon-graph-active.webp",

      iconFireInactive: "/images/home/sidebar/icon-fire-inactive.webp",
      iconFire: "/images/home/sidebar/icon-fire-active.webp",

      iconSettingInactive: "/images/home/sidebar/icon-setting-inactive.webp",
      iconSetting: "/images/home/sidebar/icon-setting-active.webp",

      iconSmileInactive: "/images/home/sidebar/icon-smile-inactive.webp",
      iconSmile: "/images/home/sidebar/icon-smile-active.webp",

      iconAppInactive: "/images/home/sidebar/icon-app-inactive.webp",
      iconApp: "/images/home/sidebar/icon-app.webp",

      iconDiscountBar: "/images/home/sidebar/icon-discount-bar-inactive.webp",

      iconCard2: "/images/home/sidebar/icon-card2.webp",
      iconSpin2: "/images/home/sidebar/icon-spin2.webp",
      iconCockfight2: "/images/home/sidebar/icon-cock-fight2.webp",
      iconFishing2: "/images/home/sidebar/icon-fishing2.webp",
      iconSport2: "/images/home/sidebar/icon-sport2.webp",
      iconLive2: "/images/home/sidebar/icon-live2.webp",
      iconSlot2: "/images/home/sidebar/icon-slot2.webp",
      iconGame2: "/images/home/sidebar/icon-game2.webp",
      iconAll2: "/images/home/sidebar/icon-all2.webp",
    },
  },
  iconBankPlaceholder: "/images/icon-bank-placeholder.webp",
  iconCheckmark: "/images/icon-checkmark.webp",
  iconCircle: "/images/icon-circle.webp",
  iconCopy: "/images/icon-copy.webp",
  iconLink: "/images/icon-link.webp",
  iconPencil: "/images/icon-pencil.webp",
  iconPhotoUpload: "/images/icon-photo-upload.webp",
  iconPlus: "/images/icon-plus.webp",
  iconRight: "/images/icon-right.webp",
  iconRing: "/images/icon-ring.webp",
  iconRing2: "/images/icon-ring2.webp",
  iconNotification: "/images/icon-notification.webp",
  iconSearch: "/images/icon-search.webp",
  iconUser: "/images/icon-user.webp",
  iconYellowClose: "/images/icon-yellow-close.webp",
  iconYellowMinus: "/images/icon-yellow-minus.webp",
  iconYellowPlus: "/images/icon-yellow-plus.webp",
  iconYellowRight: "/images/icon-yellow-right.webp",
  login: {
    bg: "/images/login/bg.webp",
    logo: "/images/logo99.webp",
    // logo: "/images/login/logo.webp",
  },
  logo911: "/images/logo99.webp",
  // logo911: "/images/logo911.webp",
  player: {
    addnew: "/images/player/addnew.webp",
  },
  profile: {
    whatsapp: "/images/profile/whatsapp.webp",
  },
  redtrash: "/images/redtrash.webp",
  safety: {
    appstore: "/images/safety/appstore.webp",
    changepin: "/images/safety/changepin.webp",
    email: "/images/safety/email.webp",
    facescan: "/images/safety/facescan.webp",
    fingerprint: "/images/safety/fingerprint.webp",
    gmail: "/images/safety/gmail.webp",
    googleStar: "/images/safety/google-star.webp",
    google: "/images/safety/google.webp",
    phone: "/images/safety/phone.webp",
    qr: "/images/safety/qr.webp",
  },
  setting: {
    iconFeedback: "/images/setting/Icon-feedback.webp",
    iconQr: "/images/setting/Icon-qr.webp",
    arrowRight: "/images/setting/arrow-right.webp",
    background: "/images/setting/background.webp",
    iconGlobe: "/images/setting/icon-globe.webp",
    iconHeadphone: "/images/setting/icon-headphone.webp",
    iconQuestion: "/images/setting/icon-question.webp",
    iconSafety: "/images/setting/icon-safety.webp",
    profile: "/images/setting/profile.webp",
    squareArrowRight: "/images/setting/square-arrow-right.webp",
    articlePerson: "/images/setting/article_person.webp",
    iconWatapps: "/images/setting/icon-watapps.webp",
    iconCs: "/images/setting/icon-cs.webp",
    iconTelegram: "/images/setting/icon-telegram.webp",
  },
  squareArrowRight: "/images/square-arrow-right.webp",
  topup: {
    moneySuccess: "/images/topup/money-success.webp",
  },
  transactions: {
    iconFilter: "/images/transactions/icon-filter.webp",
    iconRight: "/images/transactions/icon-right.webp",
    plus: "/images/transactions/plus.webp",
  },
  trash: "/images/trash.webp",
  unfavorite: "/images/unfavorite.webp",
  vip: {
    greenDiamond: "/images/vip/green-diamond.webp",
    refresh: "/images/vip/refresh.webp",
    vip0: "/images/vip/vip0.webp",
    vip1: "/images/vip/vip1.webp",
    vip10: "/images/vip/vip10.webp",
    vip2: "/images/vip/vip2.webp",
    vip3: "/images/vip/vip3.webp",
    vip4: "/images/vip/vip4.webp",
    vip5: "/images/vip/vip5.webp",
    vip6: "/images/vip/vip6.webp",
    vip7: "/images/vip/vip7.webp",
    vip8: "/images/vip/vip8.webp",
    vip9: "/images/vip/vip9.webp",
  },
  withdraw: {
    buttonmoney: "/images/withdraw/buttonmoney.webp",
    buttonstar: "/images/withdraw/buttonstar.webp",
    iconRefresh: "/images/withdraw/icon-refresh.webp",
    inputMoney: "/images/withdraw/input-money.webp",
  },
  yellowDown: "/images/yellow-down.webp",
  yellowUp: "/images/yellow-up.webp",
  blueRight: "/images/blue-right.webp",
  iconredDot: "/images/icon-red-dot.webp",
  iconBell: "/images/icon-bell.webp",
  penLine: "/images/pen-line.webp",
  iconAndroid: "/images/icon-android.webp",
  iconApple: "/images/icon-apple.webp",
  iconWeb: "/images/icon-web.webp",
  logo99: "/images/logo99.webp",
  agent: {
    androidDownload: "/images/agent/android-download.webp",
    apppleDownload: "/images/agent/appple-download.webp",
    bg: "/images/agent/bg.webp",
    buttonWeb: "/images/agent/button-web.webp",
    discount: "/images/agent/discount.webp",
    girl: "/images/agent/girl.webp",
    logo: "/images/agent/logo.webp",
    title: "/images/agent/title.webp",
    card: "/images/agent/card.webp",
    greenCard: "/images/agent/agent-green-card.webp",
    bgTop: "/images/agent/bg-top.webp",
  },

  user: {
    logo: "/images/user/logo.webp",
    girl: "/images/user/girl.webp",
    cash: "/images/user/cash.webp",
    bgTop: "/images/user/bg-top.webp",
    bgBottom: "/images/user/bg-bottom.webp",
    apppleDownload: "/images/user/appple-download.webp",
    androidDownload: "/images/user/android-download.webp",
    buttonWeb: "/images/user/button-web.webp",
  },
  common: {
    loadingBar: "/images/loading.gif",
  },
  intro: {
    logo: "/images/logo99.webp",
    banner1: "/images/intro/banner1.webp",
    button: "/images/intro/button.webp",
    girl: "/images/intro/girl.webp",
    girl2: "/images/intro/girl2.webp",
    phone: "/images/intro/phone.webp",
    player2: "/images/intro/player2.webp",
    playstore: "/images/intro/playstore.webp",
    rectangle1: "/images/intro/rectangle1.webp",
    tall: "/images/intro/tall.webp",
    video: "/images/intro/video.webp",
    campaign: "/images/intro/campaign.webp",
  },
};
